
from django.db import migrations, models


def seed_teams(apps, schema_editor):
    Teams = apps.get_model('teams', 'Teams')
    if Teams.objects.exists():
        return

    sample_teams = [
        {
            'name': 'Frontend Development',
            'lead_name': 'Alex Thompson',
            'lead_role': 'Engineering Manager',
            'lead_email': 'alex.thompson@sky.com',
            'department': 'Global Apps Engineering',
            'location': 'London, UK',
            'summary': "The Frontend Development team is responsible for creating and maintaining Sky's customer-facing web applications. We focus on delivering seamless user experiences while ensuring high performance and accessibility standards.",
            'status': 'active',
            'members_count': 12,
            'active_projects': 12,
            'repositories_count': 8,
            'dependencies_count': 5,
            'banner_start': '#c9dcff',
            'banner_end': '#e6ecff',
            'accent_color': '#5b45e7',
            'accent_soft_color': '#f3efff',
            'profile_gradient_start': '#5a18e6',
            'profile_gradient_end': '#2d6ef2',
            'contacts': [
                {'name': 'Alex Thompson', 'role': 'Engineering Manager', 'initials': 'AT'},
                {'name': 'Sarah Chen', 'role': 'Tech Lead', 'initials': 'SC'},
            ],
            'members': [
                {'name': 'Alex Thompson', 'role': 'Engineering Manager', 'group': 'engineer', 'email': 'alex.t@sky.com', 'phone': '+44 20 7123 4567', 'initials': 'AT', 'color': '#4f46e5'},
                {'name': 'Sarah Chen', 'role': 'Tech Lead', 'group': 'engineer', 'email': 'sarah.c@sky.com', 'phone': '+44 20 7123 4568', 'initials': 'SC', 'color': '#16a34a'},
                {'name': 'Emily Parker', 'role': 'Senior Engineer', 'group': 'engineer', 'email': 'emily.p@sky.com', 'phone': '+44 20 7123 4569', 'initials': 'EP', 'color': '#dc2626'},
            ],
            'repositories': [
                {'name': 'sky-frontend-components', 'description': "Core component library for Sky's frontend applications", 'tags': ['Frontend', 'React', 'TypeScript'], 'stars': 124, 'forks': 45, 'updated': 'Updated 2 days ago', 'icon': '⌘'},
                {'name': 'sky-design-system', 'description': "Documentation and guidelines for Sky's design system", 'tags': ['Docs', 'Design', 'Guidelines'], 'stars': 89, 'forks': 18, 'updated': 'Updated 5 days ago', 'icon': '⌘'},
            ],
            'dependencies': [
                {'name': 'UI/UX Design Team', 'type': 'Upstream', 'manager': 'Emily Chen', 'status': 'Active', 'color': '#5b45e7'},
                {'name': 'Backend Services Team', 'type': 'Downstream', 'manager': 'Michael Park', 'status': 'Active', 'color': '#16a34a'},
                {'name': 'Platform Team', 'type': 'Downstream', 'manager': 'Sarah Williams', 'status': 'Active', 'color': '#dc2626'},
            ],
            'quick_links': [
                {'label': 'GitHub Organization', 'url': '#'},
                {'label': 'Team Documentation', 'url': '#'},
            ],
        },
        {
            'name': 'Backend Services',
            'lead_name': 'Emily Chen',
            'lead_role': 'Tech Lead',
            'lead_email': 'emily.chen@sky.com',
            'department': 'Platform Engineering',
            'location': 'Manchester, UK',
            'summary': 'Backend Services creates secure APIs and business services that power the Sky product suite.',
            'status': 'active',
            'members_count': 15,
            'active_projects': 10,
            'repositories_count': 12,
            'dependencies_count': 4,
            'banner_start': '#e4c9ff',
            'banner_end': '#f2e6ff',
            'accent_color': '#9333ea',
            'accent_soft_color': '#f7f0ff',
            'profile_gradient_start': '#5b21b6',
            'profile_gradient_end': '#7c3aed',
            'contacts': [{'name': 'Emily Chen', 'role': 'Tech Lead', 'initials': 'EC'}],
            'members': [
                {'name': 'Emily Chen', 'role': 'Tech Lead', 'group': 'engineer', 'email': 'emily.chen@sky.com', 'phone': '+44 20 7123 4661', 'initials': 'EC', 'color': '#9333ea'},
                {'name': 'Ava Patel', 'role': 'API Architect', 'group': 'engineer', 'email': 'ava.p@sky.com', 'phone': '+44 20 7123 4662', 'initials': 'AP', 'color': '#16a34a'},
            ],
            'repositories': [{'name': 'sky-api-gateway', 'description': 'Gateway for authenticated client traffic', 'tags': ['Backend', 'Go', 'API'], 'stars': 102, 'forks': 29, 'updated': 'Updated 1 day ago', 'icon': '⌘'}],
            'dependencies': [
                {'name': 'Platform Team', 'type': 'Upstream', 'manager': 'Sarah Williams', 'status': 'Active', 'color': '#9333ea'},
                {'name': 'Security Team', 'type': 'Upstream', 'manager': 'David Park', 'status': 'Active', 'color': '#16a34a'},
            ],
            'quick_links': [{'label': 'API Reference', 'url': '#'}],
        },
        {
            'name': 'Cloud Infrastructure',
            'lead_name': 'Michael Ross',
            'lead_role': 'Infrastructure Lead',
            'lead_email': 'michael.ross@sky.com',
            'department': 'Cloud Platform',
            'location': 'Leeds, UK',
            'summary': 'Cloud Infrastructure provisions the environments, observability, and deployment pipelines that support all product teams.',
            'status': 'active',
            'members_count': 8,
            'active_projects': 6,
            'repositories_count': 6,
            'dependencies_count': 4,
            'banner_start': '#cceef1',
            'banner_end': '#e4fbfd',
            'accent_color': '#0ea5b9',
            'accent_soft_color': '#ecfeff',
            'profile_gradient_start': '#0891b2',
            'profile_gradient_end': '#14b8a6',
            'contacts': [{'name': 'Michael Ross', 'role': 'Infrastructure Lead', 'initials': 'MR'}],
            'members': [
                {'name': 'Michael Ross', 'role': 'Infrastructure Lead', 'group': 'engineer', 'email': 'michael.r@sky.com', 'phone': '+44 20 7123 4761', 'initials': 'MR', 'color': '#0ea5b9'},
                {'name': 'Sara Lee', 'role': 'SRE Lead', 'group': 'engineer', 'email': 'sara.l@sky.com', 'phone': '+44 20 7123 4762', 'initials': 'SL', 'color': '#16a34a'},
            ],
            'repositories': [{'name': 'sky-terraform-infra', 'description': 'Infrastructure-as-code for all cloud environments', 'tags': ['Terraform', 'AWS'], 'stars': 72, 'forks': 12, 'updated': 'Updated 3 days ago', 'icon': '⌘'}],
            'dependencies': [{'name': 'Security Team', 'type': 'Upstream', 'manager': 'David Park', 'status': 'Active', 'color': '#0ea5b9'}],
            'quick_links': [{'label': 'Cloud Console', 'url': '#'}],
        },
        {
            'name': 'Security Team',
            'lead_name': 'David Park',
            'lead_role': 'Security Lead',
            'lead_email': 'david.park@sky.com',
            'department': 'Security and Risk',
            'location': 'Birmingham, UK',
            'summary': 'Security Team maintains application security standards, risk reviews, and response playbooks.',
            'status': 'active',
            'members_count': 10,
            'active_projects': 7,
            'repositories_count': 5,
            'dependencies_count': 3,
            'banner_start': '#ffd0e4',
            'banner_end': '#ffe8f2',
            'accent_color': '#e11d48',
            'accent_soft_color': '#fff1f5',
            'profile_gradient_start': '#db2777',
            'profile_gradient_end': '#9333ea',
            'contacts': [{'name': 'David Park', 'role': 'Security Lead', 'initials': 'DP'}],
            'members': [
                {'name': 'David Park', 'role': 'Security Lead', 'group': 'engineer', 'email': 'david.p@sky.com', 'phone': '+44 20 7123 4861', 'initials': 'DP', 'color': '#e11d48'},
                {'name': 'Priya Shah', 'role': 'GRC Analyst', 'group': 'product', 'email': 'priya.s@sky.com', 'phone': '+44 20 7123 4862', 'initials': 'PS', 'color': '#0ea5e9'},
            ],
            'repositories': [{'name': 'sky-security-policies', 'description': 'Policy-as-code and review checklists', 'tags': ['Security', 'Policy'], 'stars': 40, 'forks': 8, 'updated': 'Updated 7 days ago', 'icon': '⌘'}],
            'dependencies': [{'name': 'Frontend Development', 'type': 'Upstream', 'manager': 'Alex Thompson', 'status': 'Active', 'color': '#e11d48'}],
            'quick_links': [{'label': 'Security Checklist', 'url': '#'}],
        },
        {
            'name': 'Mobile Development',
            'lead_name': 'Sarah Kim',
            'lead_role': 'Mobile Engineering Lead',
            'lead_email': 'sarah.kim@sky.com',
            'department': 'Product Engineering',
            'location': 'London, UK',
            'summary': 'Mobile Development owns native mobile experiences, release coordination, and app store delivery.',
            'status': 'active',
            'members_count': 9,
            'active_projects': 8,
            'repositories_count': 7,
            'dependencies_count': 3,
            'banner_start': '#e7d7ff',
            'banner_end': '#f4ecff',
            'accent_color': '#7c3aed',
            'accent_soft_color': '#f6f0ff',
            'profile_gradient_start': '#6d28d9',
            'profile_gradient_end': '#8b5cf6',
            'contacts': [{'name': 'Sarah Kim', 'role': 'Mobile Engineering Lead', 'initials': 'SK'}],
            'members': [
                {'name': 'Sarah Kim', 'role': 'Mobile Engineering Lead', 'group': 'engineer', 'email': 'sarah.k@sky.com', 'phone': '+44 20 7123 4961', 'initials': 'SK', 'color': '#7c3aed'},
                {'name': 'Jordan Miles', 'role': 'iOS Lead', 'group': 'engineer', 'email': 'jordan.m@sky.com', 'phone': '+44 20 7123 4962', 'initials': 'JM', 'color': '#16a34a'},
            ],
            'repositories': [{'name': 'sky-mobile-app', 'description': 'Shared mobile application codebase', 'tags': ['iOS', 'Android', 'React Native'], 'stars': 110, 'forks': 24, 'updated': 'Updated 2 days ago', 'icon': '⌘'}],
            'dependencies': [{'name': 'Design Team', 'type': 'Upstream', 'manager': 'Alex Thompson', 'status': 'Active', 'color': '#7c3aed'}],
            'quick_links': [{'label': 'App Store Connect', 'url': '#'}],
        },
        {
            'name': 'DevOps Team',
            'lead_name': 'James Wilson',
            'lead_role': 'DevOps Lead',
            'lead_email': 'james.wilson@sky.com',
            'department': 'Delivery Platform',
            'location': 'Remote',
            'summary': 'DevOps Team keeps delivery pipelines healthy, automates releases, and maintains environment reliability.',
            'status': 'active',
            'members_count': 6,
            'active_projects': 5,
            'repositories_count': 10,
            'dependencies_count': 4,
            'banner_start': '#ffe0d2',
            'banner_end': '#fff1e8',
            'accent_color': '#f97316',
            'accent_soft_color': '#fff6ed',
            'profile_gradient_start': '#ea580c',
            'profile_gradient_end': '#fb923c',
            'contacts': [{'name': 'James Wilson', 'role': 'DevOps Lead', 'initials': 'JW'}],
            'members': [
                {'name': 'James Wilson', 'role': 'DevOps Lead', 'group': 'engineer', 'email': 'james.w@sky.com', 'phone': '+44 20 7123 5061', 'initials': 'JW', 'color': '#f97316'},
                {'name': 'Tara Ahmed', 'role': 'Pipeline Engineer', 'group': 'engineer', 'email': 'tara.a@sky.com', 'phone': '+44 20 7123 5062', 'initials': 'TA', 'color': '#16a34a'},
            ],
            'repositories': [{'name': 'sky-ci-cd', 'description': 'CI/CD pipeline definitions and deployment automation', 'tags': ['CI', 'CD', 'DevOps'], 'stars': 77, 'forks': 16, 'updated': 'Updated 4 days ago', 'icon': '⌘'}],
            'dependencies': [{'name': 'Cloud Infrastructure', 'type': 'Upstream', 'manager': 'Michael Ross', 'status': 'Active', 'color': '#f97316'}],
            'quick_links': [{'label': 'Pipeline Dashboard', 'url': '#'}],
        },
    ]

    for team_data in sample_teams:
        Teams.objects.create(**team_data)


class Migration(migrations.Migration):
    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(model_name='teams', name='name', field=models.CharField(default='New Team', max_length=120)),
        migrations.AddField(model_name='teams', name='slug', field=models.SlugField(blank=True, max_length=140, null=True, unique=True)),
        migrations.AddField(model_name='teams', name='lead_name', field=models.CharField(default='Team Lead', max_length=120)),
        migrations.AddField(model_name='teams', name='lead_role', field=models.CharField(default='Team Lead', max_length=120)),
        migrations.AddField(model_name='teams', name='lead_email', field=models.EmailField(default='team@sky.com', max_length=254)),
        migrations.AddField(model_name='teams', name='department', field=models.CharField(default='General', max_length=120)),
        migrations.AddField(model_name='teams', name='location', field=models.CharField(default='Remote', max_length=120)),
        migrations.AddField(model_name='teams', name='summary', field=models.TextField(blank=True, default='')),
        migrations.AddField(model_name='teams', name='status', field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20)),
        migrations.AddField(model_name='teams', name='members_count', field=models.PositiveIntegerField(default=0)),
        migrations.AddField(model_name='teams', name='active_projects', field=models.PositiveIntegerField(default=0)),
        migrations.AddField(model_name='teams', name='repositories_count', field=models.PositiveIntegerField(default=0)),
        migrations.AddField(model_name='teams', name='dependencies_count', field=models.PositiveIntegerField(default=0)),
        migrations.AddField(model_name='teams', name='banner_start', field=models.CharField(default='#d8e6ff', max_length=20)),
        migrations.AddField(model_name='teams', name='banner_end', field=models.CharField(default='#c2d7ff', max_length=20)),
        migrations.AddField(model_name='teams', name='accent_color', field=models.CharField(default='#5b45e7', max_length=20)),
        migrations.AddField(model_name='teams', name='accent_soft_color', field=models.CharField(default='#f3efff', max_length=20)),
        migrations.AddField(model_name='teams', name='profile_gradient_start', field=models.CharField(default='#5a18e6', max_length=20)),
        migrations.AddField(model_name='teams', name='profile_gradient_end', field=models.CharField(default='#2d6ef2', max_length=20)),
        migrations.AddField(model_name='teams', name='contacts', field=models.JSONField(blank=True, default=list)),
        migrations.AddField(model_name='teams', name='members', field=models.JSONField(blank=True, default=list)),
        migrations.AddField(model_name='teams', name='repositories', field=models.JSONField(blank=True, default=list)),
        migrations.AddField(model_name='teams', name='dependencies', field=models.JSONField(blank=True, default=list)),
        migrations.AddField(model_name='teams', name='quick_links', field=models.JSONField(blank=True, default=list)),
        migrations.RunPython(seed_teams, migrations.RunPython.noop),
    ]
