# Generated by Django 6.0.4 on 2026-04-24 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_fields_and_seed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teams',
            options={'ordering': ['name']},
        ),
    ]
