from django.db import migrations


def refresh_teams(apps, schema_editor):
    Teams = apps.get_model("teams", "Teams")

    Teams.objects.all().delete()

    diagram_teams = [
        {
            "name": "Core Team",
            "lead_name": "Core Lead",
            "lead_role": "Architecture Lead",
            "lead_email": "core.team@sky.com",
            "department": "Architecture",
            "location": "London, UK",
            "summary": "Architecture team connecting delivery teams across the platform.",
            "members_count": 10,
            "active_projects": 6,
            "repositories_count": 4,
            "dependencies_count": 8,
            "accent_color": "#ef4444",
            "accent_soft_color": "#fff1f2",
        },
        {
            "name": "Mobile",
            "lead_name": "Mobile Lead",
            "lead_role": "Mobile Lead",
            "lead_email": "mobile@sky.com",
            "department": "Mobile",
            "location": "Remote",
            "summary": "Mobile team responsible for native app delivery.",
            "members_count": 7,
            "active_projects": 4,
            "repositories_count": 3,
            "dependencies_count": 3,
            "accent_color": "#f59e0b",
            "accent_soft_color": "#fffbeb",
        },
        {
            "name": "Team Gamma",
            "lead_name": "Gamma Lead",
            "lead_role": "DevOps Lead",
            "lead_email": "team.gamma@sky.com",
            "department": "DevOps",
            "location": "Remote",
            "summary": "DevOps-aligned team focused on release operations.",
            "members_count": 6,
            "active_projects": 5,
            "repositories_count": 4,
            "dependencies_count": 5,
            "accent_color": "#8b5cf6",
            "accent_soft_color": "#f5f3ff",
        },
        {
            "name": "Team Zeta",
            "lead_name": "Zeta Lead",
            "lead_role": "Data Lead",
            "lead_email": "team.zeta@sky.com",
            "department": "Data",
            "location": "Remote",
            "summary": "Data platform and analytics delivery team.",
            "members_count": 6,
            "active_projects": 4,
            "repositories_count": 4,
            "dependencies_count": 4,
            "accent_color": "#ec4899",
            "accent_soft_color": "#fdf2f8",
        },
        {
            "name": "Team Epsilon",
            "lead_name": "Epsilon Lead",
            "lead_role": "Security Lead",
            "lead_email": "team.epsilon@sky.com",
            "department": "Security",
            "location": "Remote",
            "summary": "Security review and protection team.",
            "members_count": 7,
            "active_projects": 4,
            "repositories_count": 3,
            "dependencies_count": 4,
            "accent_color": "#3b82f6",
            "accent_soft_color": "#eff6ff",
        },
        {
            "name": "Team Theta",
            "lead_name": "Theta Lead",
            "lead_role": "API Lead",
            "lead_email": "team.theta@sky.com",
            "department": "API",
            "location": "Remote",
            "summary": "API integration and contract design team.",
            "members_count": 6,
            "active_projects": 3,
            "repositories_count": 3,
            "dependencies_count": 4,
            "accent_color": "#8b5cf6",
            "accent_soft_color": "#f5f3ff",
        },
        {
            "name": "Team Delta",
            "lead_name": "Delta Lead",
            "lead_role": "QA Lead",
            "lead_email": "team.delta@sky.com",
            "department": "QA",
            "location": "Remote",
            "summary": "Quality assurance and test coverage team.",
            "members_count": 6,
            "active_projects": 4,
            "repositories_count": 3,
            "dependencies_count": 3,
            "accent_color": "#f97316",
            "accent_soft_color": "#fff7ed",
        },
        {
            "name": "Team Beta",
            "lead_name": "Beta Lead",
            "lead_role": "Backend Lead",
            "lead_email": "team.beta@sky.com",
            "department": "Backend",
            "location": "Remote",
            "summary": "Backend services team for platform APIs and services.",
            "members_count": 7,
            "active_projects": 5,
            "repositories_count": 5,
            "dependencies_count": 4,
            "accent_color": "#10b981",
            "accent_soft_color": "#ecfdf5",
        },
        {
            "name": "Team Alpha",
            "lead_name": "Alpha Lead",
            "lead_role": "Frontend Lead",
            "lead_email": "team.alpha@sky.com",
            "department": "Frontend",
            "location": "Remote",
            "summary": "Frontend implementation team for product surfaces.",
            "members_count": 7,
            "active_projects": 5,
            "repositories_count": 4,
            "dependencies_count": 4,
            "accent_color": "#60a5fa",
            "accent_soft_color": "#eff6ff",
        },
        {
            "name": "Backend Team",
            "lead_name": "Backend Team Lead",
            "lead_role": "Backend Lead",
            "lead_email": "backend.team@sky.com",
            "department": "Backend",
            "location": "Remote",
            "summary": "Backend delivery team shown in the collaboration map.",
            "members_count": 8,
            "active_projects": 5,
            "repositories_count": 4,
            "dependencies_count": 4,
            "accent_color": "#10b981",
            "accent_soft_color": "#ecfdf5",
        },
        {
            "name": "Security Team",
            "lead_name": "Security Team Lead",
            "lead_role": "Security Lead",
            "lead_email": "security.team@sky.com",
            "department": "Security",
            "location": "Remote",
            "summary": "Security delivery team shown in the collaboration map.",
            "members_count": 8,
            "active_projects": 5,
            "repositories_count": 4,
            "dependencies_count": 4,
            "accent_color": "#8b5cf6",
            "accent_soft_color": "#f5f3ff",
        },
        {
            "name": "Frontend Team",
            "lead_name": "Frontend Team Lead",
            "lead_role": "Frontend Lead",
            "lead_email": "frontend.team@sky.com",
            "department": "Frontend",
            "location": "Remote",
            "summary": "Frontend delivery team shown in the collaboration map.",
            "members_count": 5,
            "active_projects": 4,
            "repositories_count": 3,
            "dependencies_count": 4,
            "accent_color": "#3b82f6",
            "accent_soft_color": "#eff6ff",
        },
    ]

    for team_data in diagram_teams:
        Teams.objects.create(**team_data)


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0003_alter_teams_options"),
    ]

    operations = [
        migrations.RunPython(refresh_teams, migrations.RunPython.noop),
    ]
