# Generated by Django 5.0.2 on 2026-04-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_refresh_teams_from_diagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
