# Generated by Django 6.0.3 on 2026-04-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_teams_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='agile_practices',
            field=models.TextField(blank=True, help_text='Agile practices used by the team', null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='concurrent_projects_count',
            field=models.CharField(blank=True, help_text="Number of concurrent projects (e.g., '6+' or '5')", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='daily_standup_time_and_link',
            field=models.CharField(blank=True, help_text='Daily standup time and meeting link', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='department_head',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='dependency_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='development_focus_areas',
            field=models.TextField(blank=True, help_text='Comma-separated list of development focus areas', null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='github_repo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='jira_board_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='jira_project_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='key_skills_and_technologies',
            field=models.TextField(blank=True, help_text='Comma-separated list of key skills and technologies', null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='slack_channels',
            field=models.CharField(blank=True, help_text='Comma-separated Slack channel names', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='software_owned_and_evolved',
            field=models.TextField(blank=True, help_text='Software owned and evolved by this team', null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='team_wiki_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='versioning_approaches',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='wiki_search_terms',
            field=models.TextField(blank=True, help_text='Comma-separated search terms for team wiki', null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='workstream',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
