# Generated by Django 6.0.3 on 2026-04-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_teams_agile_practices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='dependency_links',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
