# Generated by Django 6.0.3 on 2026-03-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_departmentmanager_teamlead_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentmanager',
            name='home_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='teamlead',
            name='home_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='teammember',
            name='home_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
