# Generated by Django 6.0.3 on 2026-03-17 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_departmentmanager_home_number_teamlead_home_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentmanager',
            name='home_number',
        ),
        migrations.RemoveField(
            model_name='teamlead',
            name='home_number',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='home_number',
        ),
    ]
