# Generated by Django 6.0.4 on 2026-04-24 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_departmentmanager_home_number_and_more'),
        ('teams', '0003_alter_teams_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentmanager',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_team_members', to='teams.teams'),
        ),
        migrations.AddField(
            model_name='teamlead',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_team_members', to='teams.teams'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_team_members', to='teams.teams'),
        ),
    ]
