# Generated by Django 5.0.2 on 2026-04-28 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_departmentmanager_team_teamlead_team_teammember_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmanager',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teamlead',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('frontend_developer', 'Frontend Developer'), ('backend_developer', 'Backend Developer'), ('full_stack_developer', 'Full Stack Developer'), ('devops_engineer', 'DevOps Engineer'), ('qa_engineer', 'QA Engineer'), ('product_manager', 'Product Manager'), ('team_lead', 'Team Lead'), ('manager', 'Manager'), ('other', 'Other')], default='other', max_length=100)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('about', models.TextField(blank=True, help_text='Professional bio and background')),
                ('skills', models.JSONField(blank=True, default=list, help_text='List of technical skills')),
                ('avatar_gradient_start', models.CharField(default='#4B5BE5', help_text='Hex color for avatar gradient start', max_length=7)),
                ('avatar_gradient_end', models.CharField(default='#7B68EE', help_text='Hex color for avatar gradient end', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profile',
            },
        ),
    ]
