# Generated by Django 5.0.2 on 2026-04-28 10:53

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_delete_meetingparticipant_meeting_created_at_and_more'),
    ]

    operations = [
        # First, set default value for existing NULL created_at fields
        migrations.RunSQL(
            'UPDATE meeting SET created_at = datetime("now") WHERE created_at IS NULL',
            reverse_sql=migrations.RunSQL.noop
        ),
        # Then make the field non-nullable
        migrations.AlterField(
            model_name='meeting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
